//! The client expression contract — wire grammar v1, evaluated engine-side.
//!
//! This is NOT a second implementation of the expression language: the client
//! `ExpressionEngine` (starui `@wellsfargo-starui/core`) is the only parser, and this
//! module consumes the serialized AST (`SsrmExprNode`) that
//! `compileToEngineExpression` emits. Semantics are the CLIENT evaluator's JS
//! coercions, verbatim — `evalOps.ts` + `functions.ts`:
//!
//!   - `toNum(null | NaN-string) → 0`, but an actual NaN NUMBER passes through
//!   - `toStr(null) → ''`; the `+` operator concatenates via `${}` display
//!     semantics instead (`null` renders "null")
//!   - `isTruthy`: null / false / 0 / '' are falsy — NaN is TRUTHY (the client
//!     helper checks the five literals, not `Boolean(v)`)
//!   - `==` / `!=` are strict (`===`): no cross-type coercion
//!   - `/` by null or 0 → null (the pending-aggregate sentinel)
//!   - AND/OR return an OPERAND, not a boolean
//!
//! The normative statement of all of this is the golden fixture corpus
//! (`tests/fixtures/ssrmExpressionContract.wire.json`, generated by the starui
//! repo from `ssrmExpressionContract.fixtures.json`); `tests/expr_contract.rs`
//! runs every case. Divergence from a fixture is a bug HERE, never in the
//! fixture.

use crate::store::Value;
use serde_json::Value as Json;
use std::sync::Arc;

// ---------------------------------------------------------------- wire form

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BinOp { Add, Sub, Mul, Div, Mod, Eq, Ne, Lt, Le, Gt, Ge, And, Or }

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum UnOp { Neg, Not }

#[derive(Debug, Clone)]
pub enum Expr {
    Lit(Value),
    Col(String),
    Bin { op: BinOp, l: Box<Expr>, r: Box<Expr> },
    Un { op: UnOp, a: Box<Expr> },
    Fn { name: String, args: Vec<Expr> },
    In { a: Box<Expr>, list: Vec<Expr> },
    Between { a: Box<Expr>, lo: Box<Expr>, hi: Box<Expr> },
    Cond { branches: Vec<(Expr, Expr)>, els: Option<Box<Expr>> },
    /// `SUM([col])` and friends — a view-level scalar the whole column shares.
    Agg { func: String, col: String },
}

impl Expr {
    /// Parse a `SsrmExprNode` (`{k: 'lit'|'col'|'bin'|...}`). Unknown kinds,
    /// operators or function names are an ERROR, not a null — a spec that
    /// half-parses would filter on a different predicate than it displays.
    pub fn from_wire(j: &Json) -> Result<Expr, String> {
        let k = j.get("k").and_then(Json::as_str).ok_or("expr node without k")?;
        Ok(match k {
            "lit" => Expr::Lit(match j.get("v").unwrap_or(&Json::Null) {
                Json::Null => Value::Null,
                Json::Bool(b) => Value::Bool(*b),
                Json::Number(n) => {
                    if let Some(i) = n.as_i64() { Value::Int(i) }
                    else { Value::Float(n.as_f64().unwrap_or(f64::NAN)) }
                }
                Json::String(s) => Value::Str(Arc::from(s.as_str())),
                other => return Err(format!("non-scalar literal {other}")),
            }),
            "col" => Expr::Col(j.get("name").and_then(Json::as_str).ok_or("col without name")?.to_string()),
            "bin" => {
                let op = match j.get("op").and_then(Json::as_str).unwrap_or("") {
                    "add" => BinOp::Add, "sub" => BinOp::Sub, "mul" => BinOp::Mul,
                    "div" => BinOp::Div, "mod" => BinOp::Mod,
                    "eq" => BinOp::Eq, "ne" => BinOp::Ne,
                    "lt" => BinOp::Lt, "le" => BinOp::Le, "gt" => BinOp::Gt, "ge" => BinOp::Ge,
                    "and" => BinOp::And, "or" => BinOp::Or,
                    other => return Err(format!("unknown binary op {other:?}")),
                };
                Expr::Bin {
                    op,
                    l: Box::new(Expr::from_wire(j.get("l").ok_or("bin without l")?)?),
                    r: Box::new(Expr::from_wire(j.get("r").ok_or("bin without r")?)?),
                }
            }
            "un" => {
                let op = match j.get("op").and_then(Json::as_str).unwrap_or("") {
                    "neg" => UnOp::Neg, "not" => UnOp::Not,
                    other => return Err(format!("unknown unary op {other:?}")),
                };
                Expr::Un { op, a: Box::new(Expr::from_wire(j.get("a").ok_or("un without a")?)?) }
            }
            "fn" => {
                let name = j.get("name").and_then(Json::as_str).ok_or("fn without name")?;
                if !SCALAR_FNS.contains(&name) { return Err(format!("unknown scalar fn {name:?}")); }
                let args = j.get("args").and_then(Json::as_array).map(|a| {
                    a.iter().map(Expr::from_wire).collect::<Result<Vec<_>, _>>()
                }).transpose()?.unwrap_or_default();
                Expr::Fn { name: name.to_string(), args }
            }
            "in" => Expr::In {
                a: Box::new(Expr::from_wire(j.get("a").ok_or("in without a")?)?),
                list: j.get("list").and_then(Json::as_array).map(|a| {
                    a.iter().map(Expr::from_wire).collect::<Result<Vec<_>, _>>()
                }).transpose()?.unwrap_or_default(),
            },
            "between" => Expr::Between {
                a: Box::new(Expr::from_wire(j.get("a").ok_or("between without a")?)?),
                lo: Box::new(Expr::from_wire(j.get("lo").ok_or("between without lo")?)?),
                hi: Box::new(Expr::from_wire(j.get("hi").ok_or("between without hi")?)?),
            },
            "cond" => {
                let branches = j.get("branches").and_then(Json::as_array).ok_or("cond without branches")?
                    .iter().map(|b| {
                        Ok((
                            Expr::from_wire(b.get("when").ok_or("branch without when")?)?,
                            Expr::from_wire(b.get("then").ok_or("branch without then")?)?,
                        ))
                    }).collect::<Result<Vec<_>, String>>()?;
                let els = match j.get("else") {
                    Some(e) => Some(Box::new(Expr::from_wire(e)?)),
                    None => None,
                };
                Expr::Cond { branches, els }
            }
            "agg" => {
                let func = j.get("fn").and_then(Json::as_str).ok_or("agg without fn")?;
                if !AGG_FNS.contains(&func) { return Err(format!("unknown agg fn {func:?}")); }
                Expr::Agg {
                    func: func.to_string(),
                    col: j.get("col").and_then(Json::as_str).ok_or("agg without col")?.to_string(),
                }
            }
            other => Err(format!("unknown expr node kind {other:?}"))?,
        })
    }

    /// Every `agg` node in this expression, depth-first: `(fn, column)` pairs.
    pub fn agg_refs(&self, out: &mut Vec<(String, String)>) {
        match self {
            Expr::Agg { func, col } => out.push((func.clone(), col.clone())),
            Expr::Bin { l, r, .. } => { l.agg_refs(out); r.agg_refs(out); }
            Expr::Un { a, .. } => a.agg_refs(out),
            Expr::Fn { args, .. } => for a in args { a.agg_refs(out); },
            Expr::In { a, list } => { a.agg_refs(out); for x in list { x.agg_refs(out); } }
            Expr::Between { a, lo, hi } => { a.agg_refs(out); lo.agg_refs(out); hi.agg_refs(out); }
            Expr::Cond { branches, els } => {
                for (w, t) in branches { w.agg_refs(out); t.agg_refs(out); }
                if let Some(e) = els { e.agg_refs(out); }
            }
            Expr::Lit(_) | Expr::Col(_) => {}
        }
    }

    /// Evaluate against one row. `get` resolves a column name to its cell;
    /// `aggs` resolves an aggregate scalar (`fn`, `col`) — `Value::Null` for
    /// "pending / unknown", which is the client's sentinel too.
    pub fn eval(&self, get: &dyn Fn(&str) -> Value, aggs: &dyn Fn(&str, &str) -> Value) -> Value {
        match self {
            Expr::Lit(v) => v.clone(),
            Expr::Col(name) => get(name),
            Expr::Bin { op, l, r } => eval_bin(*op, l, r, get, aggs),
            Expr::Un { op, a } => {
                let v = a.eval(get, aggs);
                match op {
                    UnOp::Neg => Value::Float(-js_number(&v)),
                    UnOp::Not => Value::Bool(!is_truthy(&v)),
                }
            }
            Expr::Fn { name, args } => eval_fn(name, args, get, aggs),
            Expr::In { a, list } => {
                let v = a.eval(get, aggs);
                Value::Bool(list.iter().any(|x| strict_eq(&v, &x.eval(get, aggs))))
            }
            Expr::Between { a, lo, hi } => {
                let v = a.eval(get, aggs);
                let ge = js_relational(&v, &lo.eval(get, aggs), Rel::Ge);
                let le = js_relational(&v, &hi.eval(get, aggs), Rel::Le);
                Value::Bool(ge && le)
            }
            Expr::Cond { branches, els } => {
                for (when, then) in branches {
                    if is_truthy(&when.eval(get, aggs)) { return then.eval(get, aggs); }
                }
                els.as_ref().map(|e| e.eval(get, aggs)).unwrap_or(Value::Null)
            }
            Expr::Agg { func, col } => aggs(func, col),
        }
    }
}

// ------------------------------------------------------------- JS coercions

/// `Number(v)` — full JS coercion, NaN allowed through.
pub fn js_number(v: &Value) -> f64 {
    match v {
        Value::Null => 0.0,
        Value::Bool(b) => if *b { 1.0 } else { 0.0 },
        Value::Int(i) => *i as f64,
        Value::Float(f) => *f,
        Value::Str(s) => {
            let t = s.trim();
            if t.is_empty() { 0.0 } else { t.parse::<f64>().unwrap_or(f64::NAN) }
        }
    }
}

/// The client `toNum`: a real number passes through (NaN included), anything
/// else coerces with NaN collapsing to 0.
pub fn to_num(v: &Value) -> f64 {
    match v {
        Value::Int(i) => *i as f64,
        Value::Float(f) => *f,
        other => { let n = js_number(other); if n.is_nan() { 0.0 } else { n } }
    }
}

/// JS number → string (`String(n)`): integral values print without a decimal.
fn num_to_string(f: f64) -> String {
    if f.is_nan() { return "NaN".into(); }
    if f.is_infinite() { return if f > 0.0 { "Infinity".into() } else { "-Infinity".into() }; }
    if f.fract() == 0.0 && f.abs() < 9.0e15 { format!("{}", f as i64) } else { format!("{f}") }
}

/// The client `toStr`: null → ''.
pub fn to_str(v: &Value) -> String {
    match v {
        Value::Null => String::new(),
        other => js_display(other),
    }
}

/// `${v}` template-literal display — like `to_str` except null renders "null".
/// This is what the `+` operator concatenates with.
fn js_display(v: &Value) -> String {
    match v {
        Value::Null => "null".into(),
        Value::Bool(b) => if *b { "true".into() } else { "false".into() },
        Value::Int(i) => i.to_string(),
        Value::Float(f) => num_to_string(*f),
        Value::Str(s) => s.to_string(),
    }
}

/// The client `isTruthy`: exactly null / false / 0 / '' are falsy. NaN is
/// truthy (the helper checks five literals, not `Boolean(v)`).
pub fn is_truthy(v: &Value) -> bool {
    match v {
        Value::Null => false,
        Value::Bool(b) => *b,
        Value::Int(i) => *i != 0,
        Value::Float(f) => *f != 0.0, // NaN != 0.0 → truthy, matching the client
        Value::Str(s) => !s.is_empty(),
    }
}

/// Strict `===`: numbers compare numerically across Int/Float, everything else
/// needs matching types. NaN never equals.
pub fn strict_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Null, Value::Null) => true,
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Str(x), Value::Str(y)) => x == y,
        (Value::Int(_) | Value::Float(_), Value::Int(_) | Value::Float(_)) => {
            let (x, y) = (js_number(a), js_number(b));
            !x.is_nan() && x == y
        }
        _ => false,
    }
}

#[derive(Clone, Copy)]
enum Rel { Lt, Le, Gt, Ge }

/// JS abstract relational: string-to-string compares lexicographically,
/// anything else numerically with NaN → false.
fn js_relational(a: &Value, b: &Value, rel: Rel) -> bool {
    if let (Value::Str(x), Value::Str(y)) = (a, b) {
        return match rel {
            Rel::Lt => x < y, Rel::Le => x <= y, Rel::Gt => x > y, Rel::Ge => x >= y,
        };
    }
    let (x, y) = (js_number(a), js_number(b));
    if x.is_nan() || y.is_nan() { return false; }
    match rel { Rel::Lt => x < y, Rel::Le => x <= y, Rel::Gt => x > y, Rel::Ge => x >= y }
}

fn eval_bin(op: BinOp, l: &Expr, r: &Expr, get: &dyn Fn(&str) -> Value, aggs: &dyn Fn(&str, &str) -> Value) -> Value {
    // Short-circuit AND/OR return an OPERAND, exactly like the client.
    if op == BinOp::And {
        let left = l.eval(get, aggs);
        return if is_truthy(&left) { r.eval(get, aggs) } else { left };
    }
    if op == BinOp::Or {
        let left = l.eval(get, aggs);
        return if is_truthy(&left) { left } else { r.eval(get, aggs) };
    }
    let a = l.eval(get, aggs);
    let b = r.eval(get, aggs);
    match op {
        BinOp::Add => {
            if matches!(a, Value::Str(_)) || matches!(b, Value::Str(_)) {
                Value::Str(Arc::from(format!("{}{}", js_display(&a), js_display(&b)).as_str()))
            } else {
                Value::Float(js_number(&a) + js_number(&b))
            }
        }
        BinOp::Sub => Value::Float(js_number(&a) - js_number(&b)),
        BinOp::Mul => Value::Float(js_number(&a) * js_number(&b)),
        BinOp::Div => {
            // `null` is the pending-aggregate sentinel; `/ 0` must not flash Infinity.
            let zero = match &b {
                Value::Null => true,
                Value::Int(0) => true,
                Value::Float(f) => *f == 0.0,
                _ => false,
            };
            if zero { Value::Null } else { Value::Float(js_number(&a) / js_number(&b)) }
        }
        BinOp::Mod => Value::Float(js_number(&a) % js_number(&b)),
        BinOp::Eq => Value::Bool(strict_eq(&a, &b)),
        BinOp::Ne => Value::Bool(!strict_eq(&a, &b)),
        BinOp::Lt => Value::Bool(js_relational(&a, &b, Rel::Lt)),
        BinOp::Le => Value::Bool(js_relational(&a, &b, Rel::Le)),
        BinOp::Gt => Value::Bool(js_relational(&a, &b, Rel::Gt)),
        BinOp::Ge => Value::Bool(js_relational(&a, &b, Rel::Ge)),
        BinOp::And | BinOp::Or => unreachable!("handled above"),
    }
}

// ------------------------------------------------------------ scalar functions

const SCALAR_FNS: &[&str] = &[
    "ABS", "ROUND", "FLOOR", "CEIL", "SQRT", "POW", "MOD", "LOG", "EXP",
    "MIN", "MAX",
    "CONCAT", "UPPER", "LOWER", "TRIM", "LEN", "SUBSTRING", "REPLACE",
    "CONTAINS", "STARTS_WITH", "ENDS_WITH",
    "IF", "IFS", "SWITCH", "CASE",
    "ISNULL", "ISNOTNULL", "ISEMPTY",
    "YEAR", "MONTH", "DAY", "IS_WEEKDAY",
];

const AGG_FNS: &[&str] = &["sum", "avg", "count", "min", "max", "median", "stdev", "variance", "distinct_count"];

/// `Math.round` — ties go toward +∞, unlike Rust's `round`.
fn js_round(x: f64) -> f64 {
    if x.is_nan() || x.is_infinite() { return x; }
    (x + 0.5).floor()
}

fn utf16_len(s: &str) -> usize { s.encode_utf16().count() }

/// `String.prototype.substring` — negative/NaN clamp to 0, args swap if reversed.
fn js_substring(s: &str, start: f64, end: Option<f64>) -> String {
    let units: Vec<u16> = s.encode_utf16().collect();
    let n = units.len() as f64;
    let clamp = |x: f64| -> usize {
        if x.is_nan() || x < 0.0 { 0 } else if x > n { n as usize } else { x as usize }
    };
    let mut a = clamp(start);
    let mut b = clamp(end.unwrap_or(n));
    if a > b { std::mem::swap(&mut a, &mut b); }
    String::from_utf16_lossy(&units[a..b])
}

fn eval_fn(name: &str, args: &[Expr], get: &dyn Fn(&str) -> Value, aggs: &dyn Fn(&str, &str) -> Value) -> Value {
    let ev = |i: usize| args.get(i).map(|a| a.eval(get, aggs)).unwrap_or(Value::Null);
    let num = |i: usize| to_num(&ev(i));
    let s = |i: usize| to_str(&ev(i));
    match name {
        "ABS" => Value::Float(num(0).abs()),
        "ROUND" => {
            let dec = if args.len() > 1 { num(1) } else { 0.0 };
            let f = 10f64.powf(dec);
            Value::Float(js_round(num(0) * f) / f)
        }
        "FLOOR" => Value::Float(num(0).floor()),
        "CEIL" => Value::Float(num(0).ceil()),
        "SQRT" => Value::Float(num(0).sqrt()),
        "POW" => Value::Float(num(0).powf(num(1))),
        "MOD" => Value::Float(num(0) % num(1)),
        "LOG" => Value::Float(num(0).ln()),
        "EXP" => Value::Float(num(0).exp()),
        // Scalar varargs form only — the single-column-ref form is an `agg` node.
        // Math.min/max propagate NaN, unlike f64::min/max which skip it.
        "MIN" | "MAX" => {
            let nums: Vec<f64> = (0..args.len()).map(num).collect();
            if nums.is_empty() { return Value::Float(0.0); }
            if nums.iter().any(|n| n.is_nan()) { return Value::Float(f64::NAN); }
            let init = nums[0];
            let folded = nums.into_iter().fold(init, |acc, n| if name == "MIN" { acc.min(n) } else { acc.max(n) });
            Value::Float(folded)
        }
        "CONCAT" => {
            let joined: String = (0..args.len()).map(s).collect();
            Value::Str(Arc::from(joined.as_str()))
        }
        "UPPER" => Value::Str(Arc::from(s(0).to_uppercase().as_str())),
        "LOWER" => Value::Str(Arc::from(s(0).to_lowercase().as_str())),
        "TRIM" => Value::Str(Arc::from(s(0).trim())),
        "LEN" => Value::Float(utf16_len(&s(0)) as f64),
        "SUBSTRING" => {
            let end = if args.len() > 2 { Some(num(1) + num(2)) } else { None };
            Value::Str(Arc::from(js_substring(&s(0), num(1), end).as_str()))
        }
        // The client escapes `from` and replaces with a global regex — i.e. a
        // literal replace-all, which is exactly `str::replace`.
        "REPLACE" => Value::Str(Arc::from(s(0).replace(&s(1), &s(2)).as_str())),
        "CONTAINS" => Value::Bool(s(0).contains(&s(1))),
        "STARTS_WITH" => Value::Bool(s(0).starts_with(&s(1))),
        "ENDS_WITH" => Value::Bool(s(0).ends_with(&s(1))),
        // The compiler lowers conditionals to `cond` nodes; these stay for
        // robustness should a fn form ever arrive on the wire.
        "IF" => if is_truthy(&ev(0)) { ev(1) } else { ev(2) },
        "IFS" => {
            let has_default = args.len() % 2 == 1;
            let pairs = args.len() / 2;
            for i in 0..pairs {
                if is_truthy(&ev(i * 2)) { return ev(i * 2 + 1); }
            }
            if has_default { ev(args.len() - 1) } else { Value::Null }
        }
        "SWITCH" | "CASE" => {
            let target = ev(0);
            let rest = args.len() - 1;
            let has_default = rest % 2 == 1;
            let pairs = rest / 2;
            for i in 0..pairs {
                if strict_eq(&target, &ev(1 + i * 2)) { return ev(2 + i * 2); }
            }
            if has_default { ev(args.len() - 1) } else { Value::Null }
        }
        "ISNULL" => { let v = ev(0); if matches!(v, Value::Null) { ev(1) } else { v } }
        "ISNOTNULL" => Value::Bool(!matches!(ev(0), Value::Null)),
        "ISEMPTY" => Value::Bool(match ev(0) { Value::Null => true, Value::Str(s) => s.is_empty(), _ => false }),
        "YEAR" => date_part(&s(0), |y, _, _, _| y as f64),
        "MONTH" => date_part(&s(0), |_, m, _, _| m as f64),
        "DAY" => date_part(&s(0), |_, _, d, _| d as f64),
        "IS_WEEKDAY" => match parse_iso_ms(&s(0)) {
            Some(ms) => { let wd = weekday(ms); Value::Bool((1..=5).contains(&wd)) }
            None => Value::Bool(false), // NaN weekday: `day >= 1 && day <= 5` is false
        },
        other => {
            debug_assert!(false, "unknown scalar fn {other:?}");
            Value::Null
        }
    }
}

fn date_part(s: &str, pick: fn(i64, u32, u32, i64) -> f64) -> Value {
    match parse_iso_ms(s) {
        Some(ms) => {
            let (y, m, d) = civil_from_ms(ms);
            Value::Float(pick(y, m, d, ms))
        }
        None => Value::Float(f64::NAN), // Invalid Date → NaN, like the client
    }
}

// ------------------------------------------------------------------- dates

/// Parse an ISO-8601 date / datetime to epoch milliseconds (UTC). Hand-rolled:
/// the 1.78 toolchain pin rules out chrono's newer releases, and the accepted
/// grammar here is deliberately narrow — `YYYY-MM-DD`, optionally
/// `T?HH:MM[:SS[.fff]]` and a trailing `Z` or `±HH:MM` offset. A plain epoch
/// number (the shape a typed date column may carry) also parses.
pub fn parse_iso_ms(s: &str) -> Option<i64> {
    let t = s.trim();
    if t.is_empty() { return None; }
    // Already-numeric epoch (typed date columns store display string + epoch;
    // an expression built on the epoch shadow sends the number as a string).
    if t.chars().all(|c| c.is_ascii_digit() || c == '-' || c == '+') && t.len() >= 11 {
        if let Ok(ms) = t.parse::<i64>() { return Some(ms); }
    }
    let b = t.as_bytes();
    if b.len() < 10 || b[4] != b'-' || b[7] != b'-' { return None; }
    let year: i64 = t.get(0..4)?.parse().ok()?;
    let month: u32 = t.get(5..7)?.parse().ok()?;
    let day: u32 = t.get(8..10)?.parse().ok()?;
    if !(1..=12).contains(&month) || !(1..=31).contains(&day) { return None; }
    let mut ms = days_from_civil(year, month, day) * 86_400_000;
    let mut rest = &t[10..];
    if let Some(stripped) = rest.strip_prefix('T').or_else(|| rest.strip_prefix(' ')) { rest = stripped; }
    // Offset suffix first, so the time slice below is clean.
    let mut offset_min: i64 = 0;
    if let Some(stripped) = rest.strip_suffix('Z') {
        rest = stripped;
    } else if rest.len() >= 6 {
        let tail = &rest[rest.len() - 6..];
        let tb = tail.as_bytes();
        if (tb[0] == b'+' || tb[0] == b'-') && tb[3] == b':' {
            if let (Ok(h), Ok(m)) = (tail[1..3].parse::<i64>(), tail[4..6].parse::<i64>()) {
                offset_min = h * 60 + m;
                if tb[0] == b'-' { offset_min = -offset_min; }
                rest = &rest[..rest.len() - 6];
            }
        }
    }
    if !rest.is_empty() {
        let hb = rest.as_bytes();
        if hb.len() < 5 || hb[2] != b':' { return None; }
        let hh: i64 = rest.get(0..2)?.parse().ok()?;
        let mm: i64 = rest.get(3..5)?.parse().ok()?;
        let mut ss: i64 = 0;
        let mut frac: i64 = 0;
        if hb.len() >= 8 && hb[5] == b':' {
            ss = rest.get(6..8)?.parse().ok()?;
            if hb.len() > 9 && hb[8] == b'.' {
                let digits = &rest[9..];
                let take = digits.len().min(3);
                let val: i64 = digits.get(0..take)?.parse().ok()?;
                frac = val * 10i64.pow(3 - take as u32);
            }
        }
        ms += (hh * 3600 + mm * 60 + ss) * 1000 + frac;
    }
    Some(ms - offset_min * 60_000)
}

/// Days since 1970-01-01 for a civil date (Howard Hinnant's algorithm).
fn days_from_civil(y: i64, m: u32, d: u32) -> i64 {
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = (y - era * 400) as i64;
    let mp = ((m + 9) % 12) as i64;
    let doy = (153 * mp + 2) / 5 + d as i64 - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146_097 + doe - 719_468
}

/// Civil (year, month, day) from epoch ms — UTC.
fn civil_from_ms(ms: i64) -> (i64, u32, u32) {
    let z = ms.div_euclid(86_400_000) + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    (if m <= 2 { y + 1 } else { y }, m, d)
}

/// Day of week for epoch ms — 0 = Sunday, matching `Date.getDay()`.
fn weekday(ms: i64) -> u32 {
    let days = ms.div_euclid(86_400_000);
    ((days + 4).rem_euclid(7)) as u32
}

// ---------------------------------------------------- client aggregate scalars

/// One aggregate scalar with the CLIENT's fold semantics (`functions.ts`), used
/// for expression `agg` nodes. These differ from the grid's group aggregates:
/// SUM/AVG coerce every value through `toNum` (null counts as 0 and is
/// included in AVG's divisor), while COUNT/DISTINCT_COUNT skip nulls.
pub fn client_aggregate(func: &str, values: &mut dyn Iterator<Item = Value>) -> Value {
    match func {
        "count" => Value::Float(values.filter(|v| !matches!(v, Value::Null)).count() as f64),
        "distinct_count" => {
            let mut seen = std::collections::HashSet::new();
            for v in values {
                if matches!(v, Value::Null) { continue; }
                // Type-tagged key: SameValueZero keeps 5 and "5" distinct.
                let key = match &v {
                    Value::Bool(b) => format!("b{b}"),
                    Value::Int(i) => format!("n{}", *i as f64),
                    Value::Float(f) => format!("n{f}"),
                    Value::Str(s) => format!("s{s}"),
                    Value::Null => unreachable!(),
                };
                seen.insert(key);
            }
            Value::Float(seen.len() as f64)
        }
        "sum" => Value::Float(values.map(|v| to_num(&v)).sum::<f64>()),
        "avg" => {
            let nums: Vec<f64> = values.map(|v| to_num(&v)).collect();
            if nums.is_empty() { Value::Float(0.0) }
            else { Value::Float(nums.iter().sum::<f64>() / nums.len() as f64) }
        }
        "min" | "max" => {
            let nums: Vec<f64> = values.map(|v| to_num(&v)).collect();
            if nums.is_empty() { return Value::Float(0.0); }
            if nums.iter().any(|n| n.is_nan()) { return Value::Float(f64::NAN); }
            let init = nums[0];
            Value::Float(nums.into_iter().fold(init, |a, n| if func == "min" { a.min(n) } else { a.max(n) }))
        }
        "median" => {
            let mut nums: Vec<f64> = values.map(|v| to_num(&v)).collect();
            if nums.is_empty() { return Value::Float(0.0); }
            nums.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
            let mid = nums.len() / 2;
            Value::Float(if nums.len() % 2 == 0 { (nums[mid - 1] + nums[mid]) / 2.0 } else { nums[mid] })
        }
        "stdev" | "variance" => {
            let nums: Vec<f64> = values.map(|v| to_num(&v)).collect();
            if nums.len() <= 1 { return Value::Float(0.0); }
            let mean = nums.iter().sum::<f64>() / nums.len() as f64;
            let var = nums.iter().map(|n| (n - mean) * (n - mean)).sum::<f64>() / (nums.len() - 1) as f64;
            Value::Float(if func == "stdev" { var.sqrt() } else { var })
        }
        _ => Value::Null,
    }
}
