//! The client expression contract, enforced against the golden corpus.
//!
//! `fixtures/ssrmExpressionContract.wire.json` is GENERATED by the starui repo
//! (from `ssrmExpressionContract.fixtures.json`, the corpus its client tests
//! assert): each case carries the DSL source, the compiled wire AST, and the
//! CLIENT evaluator's output. This test runs the wire form through `expr::Expr`
//! and demands the same answer — a failure here is a bug in `src/expr.rs`,
//! never in the fixture. Copy the file fresh from starui when the corpus
//! grows; never hand-edit it.

use dshub::expr::{client_aggregate, Expr};
use dshub::store::Value;
use serde_json::Value as Json;

fn fixture() -> Json {
    let raw = include_str!("fixtures/ssrmExpressionContract.wire.json");
    serde_json::from_str(raw).expect("wire fixture parses")
}

fn value_of(j: &Json) -> Value {
    match j {
        Json::Null => Value::Null,
        Json::Bool(b) => Value::Bool(*b),
        Json::Number(n) => n.as_i64().map(Value::Int).unwrap_or_else(|| Value::Float(n.as_f64().unwrap_or(f64::NAN))),
        Json::String(s) => Value::Str(std::sync::Arc::from(s.as_str())),
        _ => Value::Null,
    }
}

/// Compare an evaluated Value with the fixture's expected JSON. Numbers compare
/// numerically (the client's 5 and our 5.0 are the same answer); a non-finite
/// float matches `null`, because that is what it becomes in row JSON.
fn matches_expected(got: &Value, want: &Json) -> bool {
    match (got, want) {
        (Value::Null, Json::Null) => true,
        (Value::Float(f), Json::Null) => !f.is_finite(),
        (Value::Bool(b), Json::Bool(w)) => b == w,
        (Value::Str(s), Json::String(w)) => s.as_ref() == w.as_str(),
        (Value::Int(_) | Value::Float(_), Json::Number(_)) => {
            let g = match got { Value::Int(i) => *i as f64, Value::Float(f) => *f, _ => unreachable!() };
            let w = want.as_f64().unwrap_or(f64::NAN);
            if g.is_nan() && w.is_nan() { return true; }
            (g - w).abs() <= 1e-9 * g.abs().max(w.abs()).max(1.0)
        }
        _ => false,
    }
}

#[test]
fn every_compiled_fixture_evaluates_to_the_client_answer() {
    let fx = fixture();
    let cases = fx["cases"].as_array().expect("cases array");
    let mut ran = 0;
    for case in cases {
        let name = case["name"].as_str().unwrap_or("?");
        if case["compiles"] != Json::Bool(true) {
            assert!(case.get("wire").is_none(), "{name}: non-compiling case must carry no wire form");
            continue;
        }
        let wire = case.get("wire").unwrap_or_else(|| panic!("{name}: compiling case without wire form"));
        let expr = Expr::from_wire(wire).unwrap_or_else(|e| panic!("{name}: wire did not parse: {e}"));

        let row = case.get("row").cloned().unwrap_or(Json::Object(Default::default()));
        let get = |col: &str| row.get(col).map(value_of).unwrap_or(Value::Null);

        // Aggregate scalars resolve over the case's `allRows`, with the CLIENT
        // fold semantics — the same helper the view layer uses.
        let all_rows = case.get("allRows").and_then(Json::as_array).cloned().unwrap_or_default();
        let aggs = |func: &str, col: &str| -> Value {
            let mut vals = all_rows.iter().map(|r| r.get(col).map(value_of).unwrap_or(Value::Null));
            client_aggregate(func, &mut vals)
        };

        let got = expr.eval(&get, &aggs);
        if let Some(want) = case.get("expected") {
            assert!(
                matches_expected(&got, want),
                "{name}: engine got {got:?}, client expected {want}"
            );
        }
        ran += 1;
    }
    assert!(ran >= 40, "corpus shrank: only {ran} compiled cases ran");
}

#[test]
fn unknown_node_kinds_and_fns_are_errors_not_nulls() {
    for bad in [
        serde_json::json!({"k": "mystery"}),
        serde_json::json!({"k": "fn", "name": "REGEX_MATCH", "args": []}),
        serde_json::json!({"k": "agg", "fn": "mode", "col": "px"}),
        serde_json::json!({"k": "bin", "op": "xor", "l": {"k":"lit","v":1}, "r": {"k":"lit","v":2}}),
    ] {
        assert!(Expr::from_wire(&bad).is_err(), "{bad} must be rejected");
    }
}
