//! Filter parity: the Rust engine must return exactly the row keys the JS
//! oracle returns, for the SAME deterministic corpus and the SAME filters.
//!
//! The fixture (`tests/fixtures/filter_parity.json`) was generated by running
//! `parity.mjs`'s `evalOps` — the reference calibrated against the live
//! Perspective engine — over `makeCorpus(2000)`. If Rust and JS disagree on any
//! case, the CSRM/SSRM interchangeability guarantee is broken. This is the same
//! comparison the JS parity harness makes, now spanning the language boundary.

use dshub::query::Filter;
use dshub::store::{TableCache, Value};
use serde_json::{json, Value as Json};

const DESKS: [&str; 5] = ["Govies", "EM Debt", "HY Credit", "IG Credit", "Inflation"];
const TRADERS: [&str; 5] = ["Jane Doe", "John Smith", "Sarah Williams", "Mike Johnson", "Tom Brown"];
const CCY: [&str; 5] = ["USD", "EUR", "GBP", "JPY", "AUD"];

/// A byte-for-byte port of `parity.mjs` `makeCorpus` — no RNG, so it reproduces.
fn make_corpus(n: usize) -> Vec<Json> {
    (0..n).map(|i| {
        let book = if i % 17 == 0 { json!("") }
            else if i % 29 == 0 { json!(null) }
            else { json!(format!("BOOK{:03}", i % 40)) };
        json!({
            "positionId": format!("POS-{:05}", i),
            "desk": DESKS[i % 5],
            "trader": TRADERS[(i * 7) % 5],
            "currency": CCY[(i * 3) % 5],
            "book": book,
            "dv01": (i % 100) as f64 * 12.5,
            "marketValue": 1_000_000i64 + (i % 500) as i64 * 1000 - (i % 7) as i64 * 137,
            "quantity": if i % 13 == 0 { 0i64 } else { ((i % 250) + 1) as i64 },
        })
    }).collect()
}

fn loaded_cache(corpus: &[Json]) -> TableCache {
    let mut t = TableCache::new(["positionId", "desk", "trader", "currency", "book", "dv01", "marketValue", "quantity"]);
    for row in corpus {
        let obj = row.as_object().unwrap();
        let key = obj["positionId"].as_str().unwrap();
        t.upsert(key, obj);
    }
    t
}

/// Keys of the rows matching `filter`, sorted — the comparison unit.
fn matching_keys(cache: &TableCache, filter: &Filter) -> Vec<String> {
    let mut out: Vec<String> = cache.live_slots().filter(|&slot| {
        let get = |col: &str| cache.col_index(col).map(|ci| cache.cell(slot, ci).clone()).unwrap_or(Value::Null);
        filter.matches(&get)
    }).filter_map(|slot| cache.key_at(slot).map(|k| k.to_string())).collect();
    out.sort();
    out
}

#[test]
fn rust_filter_matches_the_js_oracle_on_every_case() {
    let fixture: Json = serde_json::from_str(
        include_str!("fixtures/filter_parity.json")
    ).expect("fixture parses");

    let n = fixture["corpusN"].as_u64().unwrap() as usize;
    let corpus = make_corpus(n);
    let cache = loaded_cache(&corpus);
    assert_eq!(cache.len(), n, "every corpus row loaded");

    let mut checked = 0;
    for case in fixture["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let filter = Filter::from_json(&case["ops"]);
        let got = matching_keys(&cache, &filter);
        let want: Vec<String> = case["keys"].as_array().unwrap()
            .iter().map(|k| k.as_str().unwrap().to_string()).collect();
        assert_eq!(got.len(), want.len(), "case '{name}': count mismatch (rust {} vs js {})", got.len(), want.len());
        assert_eq!(got, want, "case '{name}': key sets differ");
        checked += 1;
    }
    assert_eq!(checked, 20, "all fixture cases exercised");
    eprintln!("filter parity: {checked} cases, {n} rows each — Rust == JS oracle");
}

use dshub::query::{aggregate_groups, filtered_slots, compare_values, AggSpec, Agg, GroupRow};

fn group_specs() -> Vec<AggSpec> {
    vec![
        AggSpec { column: "dv01".into(), agg: Agg::Sum, out: "dv01".into() },
        AggSpec { column: "marketValue".into(), agg: Agg::Avg, out: "mv".into() },
        AggSpec { column: "quantity".into(), agg: Agg::Min, out: "minq".into() },
        AggSpec { column: "quantity".into(), agg: Agg::Max, out: "maxq".into() },
    ]
}

fn fnum(v: &Value) -> f64 {
    match v { Value::Int(i) => *i as f64, Value::Float(f) => *f, _ => f64::NAN }
}

fn assert_groups_match(got: &[GroupRow], want: &Json) {
    let want = want.as_array().unwrap();
    assert_eq!(got.len(), want.len(), "group count");
    for (g, w) in got.iter().zip(want) {
        assert_eq!(g.value, Value::Str(w["value"].as_str().unwrap().into()), "group value");
        assert_eq!(g.count as u64, w["count"].as_u64().unwrap(), "group '{}' count", w["value"]);
        let eps = 1e-6;
        assert!((fnum(&g.aggregates["dv01"]) - w["dv01"].as_f64().unwrap()).abs() < eps, "sum dv01 for {}", w["value"]);
        assert!((fnum(&g.aggregates["mv"]) - w["mv"].as_f64().unwrap()).abs() < 1e-6 * w["mv"].as_f64().unwrap().abs().max(1.0), "avg mv for {}", w["value"]);
        assert_eq!(fnum(&g.aggregates["minq"]), w["minq"].as_f64().unwrap(), "min q for {}", w["value"]);
        assert_eq!(fnum(&g.aggregates["maxq"]), w["maxq"].as_f64().unwrap(), "max q for {}", w["value"]);
    }
}

fn grouped(cache: &TableCache, filter: &Filter) -> Vec<GroupRow> {
    let slots = filtered_slots(cache, filter);
    let mut g = aggregate_groups(cache, &slots, "desk", &group_specs());
    g.sort_by(|a, b| compare_values(&a.value, &b.value));
    g
}

#[test]
fn rust_group_aggregates_match_the_js_oracle() {
    let fixture: Json = serde_json::from_str(include_str!("fixtures/group_parity.json")).unwrap();
    let corpus = make_corpus(fixture["corpusN"].as_u64().unwrap() as usize);
    let cache = loaded_cache(&corpus);

    assert_groups_match(&grouped(&cache, &Filter::default()), &fixture["all_by_desk"]);

    let usd = Filter::from_json(&json!([{"column":"currency","op":"equals","value":"USD"}]));
    assert_groups_match(&grouped(&cache, &usd), &fixture["usd_by_desk"]);

    eprintln!("group parity: all-rows and filtered, by desk, 5 aggregates — Rust == JS oracle");
}
